name: fractal
description: p2p Fractal objects.
version: 0.1.0
repository: https://github.com/mnts/fractal

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  universal_file: ^1.0.0
  universal_io: ^2.2.2
  cross_file: ^0.3.3+8
  cross_file_image: ^1.1.0
  http: ^1.1.0
  dart_bs58check: ^3.0.2
  basic_utils: ^5.7.0
  # path: ^1.8.0
  idb_shim: ^2.6.4+1
  bip340: ^0.3.0
  collection: ^1.18.0
  sqlite3: ^2.7.5
  postgres: ^3.5.4
  intl: ^0.19.0
  color: ^3.0.0
  yaml: ^3.1.3
  pointycastle: ^3.9.1
  path: ^1.9.1
  crypto: ^3.0.6
  convert: ^3.1.2
  meta: ^1.16.0
  json_annotation: ^4.9.0
  logging: ^1.3.0


dev_dependencies:
  lints: ^5.1.1
